name: Basic Test
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: install deps
        run: |
          pip install -r requirements.txt
      - name: Run Python tests
        run: |
          python manage.py test

